### ISSUE TITLE
Define Piece Position using YOLO and Aruco Markers

### ISSUE THREAD

**Issue by JELAshford** [OxRAMSociety/OxRAM-Robot-Arm#2]
## Description

Localising the 3D location of the chess pieces on/off the board requires identifying the piece in the camera frame, and converting that 2D position into the 3D relative coordinates. We believe that this can be done by using known positions from Aruco Markers placed around the board.

## Details

Ensure that distances between Aruco markers are measured in the units used by RViz. Match the length-scales of our Computer Vision and Motion Planning systems. 

## Roadmap

- [ ] Research previous 3D localisation using space markers 
- [ ] Implement basic position tracking
- [ ] Scale this to all points in images
- [ ] Implement memory of board layout/use this to confirm estimates

**Comment by dyamon** [comment]
Following OpenCV and [this](https://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_calib3d/py_calibration/py_calibration.html#calibration) (rather outdated) tutorial we were able to perform a calibration of the camera computing **intrinsic**, **extrinsic** and distortion parameters of the camera in use.

![calib](https://user-images.githubusercontent.com/6771224/118405580-8f32de00-b670-11eb-9ded-fc757df1aa9e.jpg)

Calibration is performed using a grid of know size and the resulting parameters can be computed once and stored for future use.

Once the camera is calibrated we can interact with the camera feed and introduce some augmented reality features.

![cube](https://user-images.githubusercontent.com/6771224/118405524-37947280-b670-11eb-9a78-b94a5d8b24b8.gif)
